language: objective-c
osx_image: xcode10
cache:
  bundler: true
  cocoapods: true
  directories:
    - vendor/bundle
    - Pods
before_install:
  - xcrun instruments -s devices
  - xcrun instruments -w "iPhone X (12.0) [" || true
install:
  - bundle install --jobs=3 --retry=3 --deployment
  - bundle exec pod install
before_script:
  - if [ -n "$DANGER_GITHUB_API_TOKEN" ]; then bundle exec danger; fi
script:
  - make -B test
  - make -B carthage
  - make -B docs
after_success:
  - ruby scripts/update-docs.rb
notifications:
  email: false
  slack:
    secure: MJGlCCPZrGNkehqNxphGwKQ3eBXSzX5le94xXIsmBNejdezoOMa/c8SiNJjZk+zYgIpriKSaH5GizhYspqFZlpcdIWyRp7l5K0hdnVVgLGfdumm4DtHaK9SkhUi7Zhfs1BZamEzeH4IZ/vJ/no75BsPa2DUu0lYVZLjKSo73Cvi4OngeOxeg7WHAUDyUZExw4SAaVJHEJuQUi+kQMIO940+7m2AEWYWb2rq+Ep0KBd6V3xskt6hK6uT5jeU9CeoowD5KNqAP8fJEm3KpG3KnjwROhSfWuESVURei0uUNKxlpGGIUQD0xIYM2RtuX46VbmstXsuzWLlm8kpRLknoshYbU8DQEFsBr09yvG6Xa3A4S5103As/dFLZ0y+UIdbzT3NeZt/0VgwkBNIvKJTwQgy8Zx+uxVXuUWVIY+4KETIbi8HOAyFLAJjP8Kg/yIrt/J486+m79DSP3wfDgv4HBgiByxtA7ciCxnvEJhDFVsd481Bw7sCCnhAigH3R/oeOCDtWwYYsOynK94sCjtl3dhYf3IanhQz+Ix8Z7z86j60fslZrd0/44WtaZGqDFI6mVC0HNhCLBJ+TZfKxJ+R23hL+iIoiV7KCpAtvPwV/aDfOvluWpoKOgfKd/OW3DJVTtVZcfOmivUTCbMW+9eTjYRbJEFpiVfkpaIYW2JcgIJxY=
